//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public System.Guid catID { get; set; }
        public string catName { get; set; }
        public string catDescription { get; set; }
        public Nullable<System.DateTime> catCreatedOn { get; set; }
        public string catCreatedBy { get; set; }
        public Nullable<System.DateTime> catModifiedOn { get; set; }
        public string catModifiedBy { get; set; }
        public Nullable<bool> catIsDeleted { get; set; }
        public Nullable<bool> catIsActive { get; set; }
    }
}
