//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantAddress
    {
        public System.Guid merAddID { get; set; }
        public string merID { get; set; }
        public string merAddAddress { get; set; }
        public string merAddCity { get; set; }
        public string merAddState { get; set; }
        public string merAddCountry { get; set; }
        public string merAddZipcode { get; set; }
        public string merAddBuildingNo { get; set; }
        public string merAddAptNo { get; set; }
        public string merAddArea { get; set; }
        public string merAddLandMark { get; set; }
        public string merAddType { get; set; }
        public Nullable<System.DateTime> merAddCreatedOn { get; set; }
        public string merAddCreatedBy { get; set; }
        public Nullable<System.DateTime> merAddModifiedOn { get; set; }
        public string merAddModifiedBy { get; set; }
        public Nullable<bool> merAddIsDeleted { get; set; }
        public Nullable<bool> merAddIsActive { get; set; }
    }
}
