//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantCardInfo
    {
        public System.Guid merCarInfID { get; set; }
        public string merID { get; set; }
        public string merCarInfCardNo { get; set; }
        public string merCarInfCardName { get; set; }
        public string merCarInfExpMonth { get; set; }
        public string merCarInfExpYear { get; set; }
        public Nullable<System.DateTime> merCarInfCreatedOn { get; set; }
        public string merCarInfCreatedBy { get; set; }
        public Nullable<System.DateTime> merCarInfModifiedOn { get; set; }
        public string merCarInfModifiedBy { get; set; }
        public Nullable<bool> merCarInfIsDeleted { get; set; }
        public Nullable<bool> merCarInfIsActive { get; set; }
    }
}
