//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesMain
    {
        public System.Guid mesID { get; set; }
        public string mesSubject { get; set; }
        public string mesDetail { get; set; }
        public string mesTo { get; set; }
        public string mesBy { get; set; }
        public string mesCreatedDate { get; set; }
        public string mesTypeID { get; set; }
        public Nullable<bool> mesIsActive { get; set; }
        public Nullable<bool> mesIsRead { get; set; }
        public Nullable<bool> mesIsReadMer { get; set; }
        public int mesOrderNo { get; set; }
    }
}
