//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageThread
    {
        public System.Guid mesThreadID { get; set; }
        public string mesID { get; set; }
        public string mesThreadDetail { get; set; }
        public string mesThreadBy { get; set; }
        public string mesThreadCreatedDate { get; set; }
        public int mesThreadOrderNo { get; set; }
    }
}
