//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nationality
    {
        public System.Guid natID { get; set; }
        public string natName { get; set; }
        public string natNameAr { get; set; }
        public Nullable<System.DateTime> natCreatedOn { get; set; }
        public string natCreatedBy { get; set; }
        public Nullable<System.DateTime> natModifiedOn { get; set; }
        public string natModifiedBy { get; set; }
        public Nullable<bool> natIsDeleted { get; set; }
        public Nullable<bool> natIsActive { get; set; }
    }
}
