//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferType
    {
        public System.Guid offTypID { get; set; }
        public string offTypName { get; set; }
        public Nullable<System.DateTime> offTypCreatedOn { get; set; }
        public string offTypCreatedBy { get; set; }
        public Nullable<System.DateTime> offTypModifiedOn { get; set; }
        public string offTypModifiedBy { get; set; }
        public Nullable<bool> offTypIsDeleted { get; set; }
        public Nullable<bool> offTypIsActive { get; set; }
    }
}
