//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid ordDetID { get; set; }
        public string ordID { get; set; }
        public string proID { get; set; }
        public string invVarID { get; set; }
        public Nullable<double> ordDetPriceOriginalPrice { get; set; }
        public Nullable<double> ordDetPriceOriginalDisPrice { get; set; }
        public Nullable<double> ordDetProPrice { get; set; }
        public Nullable<double> ordDetProQty { get; set; }
        public Nullable<double> ordDetTotalPrice { get; set; }
        public string ordDetWingRefNo { get; set; }
        public Nullable<bool> ordPickUp { get; set; }
        public Nullable<double> ordDetProDiscount { get; set; }
        public string ordDetcusAddrID { get; set; }
        public string ordDetPaymentID { get; set; }
        public Nullable<double> ordDetSubTotal { get; set; }
        public Nullable<double> ordDetDisTotal { get; set; }
        public Nullable<double> ordDetFinalTotal { get; set; }
        public Nullable<double> ordDetProDefaultPrice { get; set; }
        public string ordDetStoID { get; set; }
        public Nullable<System.DateTime> ordDetCreatedOn { get; set; }
        public string ordDetCreatedBy { get; set; }
        public Nullable<System.DateTime> ordDetModifiedOn { get; set; }
        public string ordDetModifiedBy { get; set; }
        public Nullable<int> ordDetStatus { get; set; }
        public Nullable<bool> ordDetIsDeleted { get; set; }
        public Nullable<bool> ordDetIsActive { get; set; }
        public Nullable<bool> ordPersonalDel { get; set; }
        public Nullable<double> ordDelCharges { get; set; }
        public Nullable<double> ordDelChargeOriginal { get; set; }
        public string ordDetDelNote { get; set; }
        public string ordDetWingCorTyp { get; set; }
        public string ordDeliveryType { get; set; }
    }
}
