//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid ordID { get; set; }
        public string cusID { get; set; }
        public string stoID { get; set; }
        public string cusAddID { get; set; }
        public string payTypID { get; set; }
        public string delMapID { get; set; }
        public string ordNumber { get; set; }
        public Nullable<System.DateTime> ordDatetime { get; set; }
        public string ordStatus { get; set; }
        public string ordDeliveryType { get; set; }
        public string ordDeliveryTime { get; set; }
        public string ordCancelRemark { get; set; }
        public Nullable<double> ordSubTotal { get; set; }
        public Nullable<double> ordTotalDiscount { get; set; }
        public Nullable<double> ordDeliveryCharges { get; set; }
        public Nullable<double> ordTotalTax { get; set; }
        public Nullable<double> ordCreditPayment { get; set; }
        public Nullable<double> ordCashPayment { get; set; }
        public Nullable<double> ordGrandTotal { get; set; }
        public string ordOfferCode { get; set; }
        public string ordPaymentStatus { get; set; }
        public string ordFrom { get; set; }
        public string ordSignature { get; set; }
        public Nullable<decimal> ordTaxPer { get; set; }
        public Nullable<System.DateTime> ordCreatedOn { get; set; }
        public string ordCreatedBy { get; set; }
        public Nullable<System.DateTime> ordModifiedOn { get; set; }
        public string ordModifiedBy { get; set; }
        public Nullable<bool> ordIsDeleted { get; set; }
        public Nullable<bool> ordIsActive { get; set; }
    }
}
