//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDiscountDetail
    {
        public System.Guid ordDisDetID { get; set; }
        public string ordID { get; set; }
        public string stoOffID { get; set; }
        public Nullable<System.DateTime> ordDisDetCreatedOn { get; set; }
        public string ordDisDetCreatedBy { get; set; }
        public Nullable<System.DateTime> ordDisDetModifiedOn { get; set; }
        public string ordDisDetModifiedBy { get; set; }
        public Nullable<bool> ordDisDetIsDeleted { get; set; }
        public Nullable<bool> ordDisDetIsActive { get; set; }
    }
}
