//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersPayment
    {
        public System.Guid ordPayID { get; set; }
        public string ordID { get; set; }
        public string ordPayTransactionID { get; set; }
        public string ordPayTransactionNo { get; set; }
        public string ordPayTransactionStatus { get; set; }
        public Nullable<double> ordPayAmount { get; set; }
        public Nullable<System.DateTime> ordPayCreatedOn { get; set; }
        public string ordPayCreatedBy { get; set; }
        public Nullable<System.DateTime> ordPayModifiedOn { get; set; }
        public string ordPayModifiedBy { get; set; }
        public Nullable<bool> ordPayIsDeleted { get; set; }
        public Nullable<bool> ordPayIsActive { get; set; }
    }
}
