//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public System.Guid pacID { get; set; }
        public string pacName { get; set; }
        public string pacDescription { get; set; }
        public Nullable<int> pacStoresCount { get; set; }
        public Nullable<int> pacCategoriesCount { get; set; }
        public Nullable<int> pacProductCount { get; set; }
        public Nullable<double> pacPrice { get; set; }
        public string pacType { get; set; }
        public string taxID { get; set; }
        public Nullable<double> pacTaxValue { get; set; }
        public Nullable<double> pacTaxAmount { get; set; }
        public string disID { get; set; }
        public Nullable<double> pacDisValue { get; set; }
        public Nullable<double> pacDisAmount { get; set; }
        public Nullable<double> pacFinalPrice { get; set; }
        public Nullable<System.DateTime> pacCreatedOn { get; set; }
        public string pacCreatedBy { get; set; }
        public Nullable<System.DateTime> pacModifiedOn { get; set; }
        public string pacModifiedBy { get; set; }
        public Nullable<bool> pacIsDeleted { get; set; }
        public Nullable<bool> pacIsActive { get; set; }
    }
}
