//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public System.Guid payTypID { get; set; }
        public string payTypName { get; set; }
        public string payTypNameAr { get; set; }
        public string payTypDescription { get; set; }
        public string payTypDescriptionAr { get; set; }
        public string payTypIcon { get; set; }
        public Nullable<System.DateTime> payTypCreatedOn { get; set; }
        public string payTypCreatedBy { get; set; }
        public Nullable<System.DateTime> payTypModifiedOn { get; set; }
        public string payTypModifiedBy { get; set; }
        public Nullable<bool> payTypIsDeleted { get; set; }
        public Nullable<bool> payTypIsActive { get; set; }
    }
}
