//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsInfo
    {
        public System.Guid payInfID { get; set; }
        public string merID { get; set; }
        public string payTypID { get; set; }
        public string payInfTransactionNo { get; set; }
        public string payInfTransactionStatus { get; set; }
        public Nullable<System.DateTime> payInfDate { get; set; }
        public Nullable<double> payInfPrice { get; set; }
        public Nullable<double> payInfTaxAmount { get; set; }
        public Nullable<double> payInfDisAmount { get; set; }
        public Nullable<double> payInfFinalPrice { get; set; }
        public Nullable<System.DateTime> payInfCreatedOn { get; set; }
        public string payinfCreatedBy { get; set; }
        public Nullable<System.DateTime> payInfModifiedOn { get; set; }
        public string payInfModifiedBy { get; set; }
        public Nullable<bool> payInfIsDeleted { get; set; }
        public Nullable<bool> payInfIsActive { get; set; }
    }
}
