//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductContain
    {
        public System.Guid proConID { get; set; }
        public string catID { get; set; }
        public string proConName { get; set; }
        public string proConNameAr { get; set; }
        public string proConSeoName { get; set; }
        public string proConDescription { get; set; }
        public string proConIcon { get; set; }
        public Nullable<int> proSortNo { get; set; }
        public Nullable<System.DateTime> proConCreatedOn { get; set; }
        public string proConCreatedBy { get; set; }
        public Nullable<System.DateTime> proConModifiedOn { get; set; }
        public string proConModifedBy { get; set; }
        public Nullable<bool> proConIsDeleted { get; set; }
        public Nullable<bool> proConIsActive { get; set; }
    }
}
