//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductContainsMapping
    {
        public System.Guid proConMapID { get; set; }
        public string proID { get; set; }
        public string proConID { get; set; }
        public Nullable<System.DateTime> proConMapCreatedOn { get; set; }
        public string proConMapCreatedBy { get; set; }
    }
}
