//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid proID { get; set; }
        public string stoID { get; set; }
        public string catID { get; set; }
        public string stoTaxID { get; set; }
        public string stoDisID { get; set; }
        public string proCode { get; set; }
        public string proType { get; set; }
        public string proName { get; set; }
        public string proNameArb { get; set; }
        public string proSeoName { get; set; }
        public string proDescription { get; set; }
        public string proDescriptionArb { get; set; }
        public string proImg { get; set; }
        public Nullable<double> proDefaultPrice { get; set; }
        public Nullable<double> proAvailableQty { get; set; }
        public Nullable<double> proPerDayQty { get; set; }
        public string prodTimID { get; set; }
        public string proMetaKeyword { get; set; }
        public string proMetaKeywordArb { get; set; }
        public string proMetaDescription { get; set; }
        public string proMetaDescriptionArb { get; set; }
        public Nullable<bool> proHideFromShop { get; set; }
        public string excRetTimID { get; set; }
        public Nullable<bool> proBuyResShipCost { get; set; }
        public Nullable<bool> proIamResShipCost { get; set; }
        public Nullable<double> proDisValue { get; set; }
        public Nullable<double> proDisAmount { get; set; }
        public Nullable<double> proFinalAmount { get; set; }
        public Nullable<bool> proIsRecomemded { get; set; }
        public Nullable<int> proWeight { get; set; }
        public Nullable<bool> proIsPopular { get; set; }
        public Nullable<bool> proIsSubmitted { get; set; }
        public Nullable<bool> proIsApproved { get; set; }
        public Nullable<System.DateTime> proCreatedOn { get; set; }
        public string proCreatedBy { get; set; }
        public Nullable<System.DateTime> proModifiedOn { get; set; }
        public string proModifiedBy { get; set; }
        public Nullable<bool> proIsDeleted { get; set; }
        public Nullable<bool> proIsActive { get; set; }
    }
}
