//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTime
    {
        public System.Guid prodTimID { get; set; }
        public string prodTimName { get; set; }
        public string prodTimNameAr { get; set; }
        public Nullable<int> prodTimDays { get; set; }
        public Nullable<System.DateTime> prodTimCreatedOn { get; set; }
        public string prodTimCreatedBy { get; set; }
        public Nullable<System.DateTime> prodTimModifiedOn { get; set; }
        public string prodTimModifiedBy { get; set; }
        public Nullable<bool> prodTimIsDeleted { get; set; }
        public Nullable<bool> prodTimIsActive { get; set; }
    }
}
