//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingProduct
    {
        public System.Guid proRatID { get; set; }
        public string proID { get; set; }
        public string cusID { get; set; }
        public string ordID { get; set; }
        public string proRatRemarks { get; set; }
        public Nullable<int> proRatValue { get; set; }
        public Nullable<System.DateTime> proRatDate { get; set; }
        public Nullable<System.DateTime> proRatCreatedOn { get; set; }
        public string proRatCreatedBy { get; set; }
        public Nullable<System.DateTime> proRatModifiedOn { get; set; }
        public string proRatModifiedBy { get; set; }
        public Nullable<bool> proRatIsDeleted { get; set; }
        public Nullable<bool> proRatIsActive { get; set; }
    }
}
