//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public System.Guid ratID { get; set; }
        public string stoID { get; set; }
        public string cusID { get; set; }
        public string ordID { get; set; }
        public string ratRemarks { get; set; }
        public int ratValue { get; set; }
        public Nullable<System.DateTime> ratDate { get; set; }
        public Nullable<System.DateTime> ratCreatedOn { get; set; }
        public string ratCreatedBy { get; set; }
        public Nullable<System.DateTime> ratModifiedOn { get; set; }
        public string ratModifiedBy { get; set; }
        public Nullable<bool> ratIsDeleted { get; set; }
        public Nullable<bool> ratIsActive { get; set; }
    }
}
