//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        public System.Guid resID { get; set; }
        public string resName { get; set; }
        public string resNameAr { get; set; }
        public Nullable<System.DateTime> resCreatedOn { get; set; }
        public string resCreatedBy { get; set; }
        public Nullable<System.DateTime> resModifiedOn { get; set; }
        public string resModifiedBy { get; set; }
        public Nullable<bool> resIsDeleted { get; set; }
        public Nullable<bool> resIsActive { get; set; }
    }
}
