//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesMapping
    {
        public System.Guid rolMapID { get; set; }
        public string admRegID { get; set; }
        public string rolID { get; set; }
        public Nullable<System.DateTime> rolMapCreatedOn { get; set; }
        public string rolMapCreatedBy { get; set; }
        public Nullable<System.DateTime> rolMapModifiedOn { get; set; }
        public string rolMapModifiedBy { get; set; }
        public Nullable<bool> rolMapIsDeleted { get; set; }
        public Nullable<bool> rolMapIsActive { get; set; }
    }
}
