//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public System.Guid rolID { get; set; }
        public string rolName { get; set; }
        public Nullable<System.DateTime> rolCreatedOn { get; set; }
        public string rolCreatedBy { get; set; }
        public Nullable<System.DateTime> rolModifiedOn { get; set; }
        public string rolModifiedBy { get; set; }
        public Nullable<bool> rolIsDeleted { get; set; }
        public Nullable<bool> rolIsActive { get; set; }
    }
}
