//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMediaMaster
    {
        public System.Guid socMedMasID { get; set; }
        public string socMedMasName { get; set; }
        public string socMedMasNameAr { get; set; }
        public string socMedMasIcon { get; set; }
        public Nullable<System.DateTime> socMedCreatedOn { get; set; }
        public string socMedCreatedBy { get; set; }
        public Nullable<System.DateTime> socMedModifiedOn { get; set; }
        public string socMedModifiedBy { get; set; }
        public Nullable<bool> socMedMasIsDeleted { get; set; }
        public Nullable<bool> socMedMasIsActive { get; set; }
    }
}
