//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public System.Guid socMedID { get; set; }
        public string socMedMasID { get; set; }
        public string stoID { get; set; }
        public string socMedName { get; set; }
        public string socMedLink { get; set; }
        public Nullable<System.DateTime> socMedCreatedOn { get; set; }
        public string socMedCreatedBy { get; set; }
        public Nullable<System.DateTime> socMedModifiedOn { get; set; }
        public string socMedModifiedBy { get; set; }
        public Nullable<bool> socMedIsDeleted { get; set; }
        public Nullable<bool> socMedIsActive { get; set; }
    }
}
