//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public System.Guid spoID { get; set; }
        public string spoName { get; set; }
        public string spoDescription { get; set; }
        public string spoImg { get; set; }
        public string spoLink { get; set; }
        public string spoSeoName { get; set; }
        public Nullable<System.DateTime> spoCreatedOn { get; set; }
        public string spoCreatedBy { get; set; }
        public Nullable<System.DateTime> spoModifiedOn { get; set; }
        public string spoModifiedBy { get; set; }
        public Nullable<bool> spoIsDeleted { get; set; }
        public Nullable<bool> spoIsActive { get; set; }
    }
}
