//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresGallary
    {
        public System.Guid stoGalID { get; set; }
        public string stoID { get; set; }
        public string stoGalImgName { get; set; }
        public Nullable<System.DateTime> stoGalCreatedOn { get; set; }
        public string stoGalCreatedBy { get; set; }
        public Nullable<System.DateTime> stoGalModifiedOn { get; set; }
        public string stoGalModifiedBy { get; set; }
        public Nullable<bool> stoGalIsDeleted { get; set; }
        public Nullable<bool> stoGalIsActive { get; set; }
    }
}
