//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOffre
    {
        public System.Guid stoOffID { get; set; }
        public string stoID { get; set; }
        public string offTypID { get; set; }
        public string proID { get; set; }
        public string stoOffImg { get; set; }
        public string stoOffDesc { get; set; }
        public string stoOffLink { get; set; }
        public string stoOffType { get; set; }
        public string stoOffExtInt { get; set; }
        public string stoOffCode { get; set; }
        public Nullable<System.DateTime> stoOffFromDate { get; set; }
        public Nullable<System.DateTime> stoOffToDate { get; set; }
        public Nullable<double> stoOffDiscount { get; set; }
        public Nullable<double> stoOffMinAmt { get; set; }
        public string stoOffMsg { get; set; }
        public Nullable<int> stoOffOrderCount { get; set; }
        public Nullable<System.DateTime> stoOffCreatedOn { get; set; }
        public string stoOffCreatedBy { get; set; }
        public Nullable<System.DateTime> stoOffModifiedOn { get; set; }
        public string stoOffModifiedBy { get; set; }
        public Nullable<bool> stoOffIsDeleted { get; set; }
        public Nullable<bool> stoOffIsActive { get; set; }
    }
}
