//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreFavroty
    {
        public System.Guid stoFavID { get; set; }
        public string stoID { get; set; }
        public string cusID { get; set; }
        public Nullable<System.DateTime> stoFavCreatedOn { get; set; }
    }
}
