//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public System.Guid stoID { get; set; }
        public string merID { get; set; }
        public string curID { get; set; }
        public string couID { get; set; }
        public string shoCatID { get; set; }
        public string lanID { get; set; }
        public string lanIDArb { get; set; }
        public string stoName { get; set; }
        public string stoDescription { get; set; }
        public string stoArbName { get; set; }
        public string stoArbDescription { get; set; }
        public string stoEmailID { get; set; }
        public string stoContactNo { get; set; }
        public string stoOwnerName { get; set; }
        public string stoImgName { get; set; }
        public string stoLogo { get; set; }
        public string stoBgImgName { get; set; }
        public string stoAdminEmails { get; set; }
        public string stoAdminCCEmails { get; set; }
        public string stoSMTPEmail { get; set; }
        public string stoSMTPPassword { get; set; }
        public Nullable<int> stoSMTPPort { get; set; }
        public Nullable<bool> stoSMTPSSL { get; set; }
        public string stoSeoName { get; set; }
        public string stoLink { get; set; }
        public Nullable<bool> stoApproved { get; set; }
        public Nullable<bool> stoPublished { get; set; }
        public Nullable<bool> stoInventory { get; set; }
        public string stoTimeZone { get; set; }
        public string stoMetaKeyword { get; set; }
        public string stoMetaDescription { get; set; }
        public Nullable<System.DateTime> stoCreatedOn { get; set; }
        public string stoCreatedBy { get; set; }
        public string stoModifiedOn { get; set; }
        public string stoModifiedBy { get; set; }
        public Nullable<bool> stoIsDeleted { get; set; }
        public Nullable<bool> stoIsActive { get; set; }
        public Nullable<bool> stoIsClosed { get; set; }
        public string stoShopPolicies { get; set; }
        public Nullable<double> stoDeliveryCharges { get; set; }
        public string stoShopStatus { get; set; }
        public Nullable<System.DateTime> stoStartDate { get; set; }
        public Nullable<System.DateTime> stoEndDate { get; set; }
        public string stoStartTime { get; set; }
        public string stoEndTime { get; set; }
        public Nullable<bool> stoIsAcceptOrder { get; set; }
        public Nullable<bool> stoCheckoutdisable { get; set; }
        public string ngoID { get; set; }
    }
}
