//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePaymentType
    {
        public System.Guid stoPayTypID { get; set; }
        public string stoID { get; set; }
        public string payTypID { get; set; }
        public Nullable<System.DateTime> stoPayTypCreatedOn { get; set; }
        public string stoPayTypCreatedBy { get; set; }
        public Nullable<System.DateTime> stoPayTypModifiedOn { get; set; }
        public string stoPayTypModifiedBy { get; set; }
        public Nullable<bool> stoPayTypIsDeleted { get; set; }
        public Nullable<bool> stoPayTypIsActive { get; set; }
    }
}
