//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDeliveryMapping
    {
        public string stoDelMapID { get; set; }
        public string stoID { get; set; }
        public string citID { get; set; }
        public Nullable<double> stoDelMapAmt { get; set; }
        public Nullable<bool> stoDelIsEnabled { get; set; }
    }
}
