//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAddress
    {
        public System.Guid stoAddID { get; set; }
        public string stoID { get; set; }
        public string citID { get; set; }
        public string stoAddAddress { get; set; }
        public Nullable<int> stoBVType { get; set; }
        public string stoAddCity { get; set; }
        public string stoAddState { get; set; }
        public string stoAddCountry { get; set; }
        public string stoAddZipcode { get; set; }
        public string stoAddArea { get; set; }
        public string StoAddBuilding { get; set; }
        public string stoAddAptNo { get; set; }
        public string stoAddLongitude { get; set; }
        public string stoAddLatitude { get; set; }
        public string stoAddType { get; set; }
        public string stoAddStreet { get; set; }
        public string stoAddFloor { get; set; }
        public Nullable<bool> stoAddShowMyLoc { get; set; }
        public Nullable<bool> stoAddAvailablePikup { get; set; }
        public Nullable<System.DateTime> stoAddCreatedOn { get; set; }
        public string stoAddCreatedBy { get; set; }
        public Nullable<System.DateTime> stoAddModifiedOn { get; set; }
        public string stoAddModifiedBy { get; set; }
        public Nullable<bool> stoAddIsDeleted { get; set; }
        public Nullable<bool> stoAddIsActive { get; set; }
        public Nullable<bool> stoPersonalDelAvl { get; set; }
        public string stoPersonalDelCitID { get; set; }
    }
}
