//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public System.Guid taxID { get; set; }
        public string taxName { get; set; }
        public string taxType { get; set; }
        public Nullable<double> taxValue { get; set; }
        public Nullable<System.DateTime> taxCreatedOn { get; set; }
        public string taxCreatedBy { get; set; }
        public Nullable<System.DateTime> taxModifiedOn { get; set; }
        public string taxModifiedBy { get; set; }
        public Nullable<bool> taxIsDeleted { get; set; }
        public Nullable<bool> taxIsActive { get; set; }
    }
}
