//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackOrder
    {
        public System.Guid traOrdID { get; set; }
        public string ordDetID { get; set; }
        public Nullable<int> ordStaID { get; set; }
        public string traOrdText { get; set; }
        public Nullable<System.DateTime> traOrdDate { get; set; }
        public Nullable<System.DateTime> traOrdCreatedOn { get; set; }
        public string traOrdCreatedBy { get; set; }
        public Nullable<System.DateTime> traOrdModifiedOn { get; set; }
        public string traOrdModifiedBy { get; set; }
        public Nullable<bool> traOrdIsDeleted { get; set; }
        public Nullable<bool> traOrdIsActive { get; set; }
    }
}
