//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekDay
    {
        public System.Guid weeDayID { get; set; }
        public string weeDayName { get; set; }
        public string weeDayNameAr { get; set; }
        public Nullable<System.DateTime> weeDayCreatedOn { get; set; }
        public string weeDayCreatedBy { get; set; }
        public Nullable<System.DateTime> weeDayModifiedOn { get; set; }
        public string weeDayModifiedBy { get; set; }
        public Nullable<bool> weeDayIsDeleted { get; set; }
        public Nullable<bool> weeDayIsActive { get; set; }
        public Nullable<int> weeDaySort { get; set; }
    }
}
